all: Event_Generator_Function_PYTHIA.C
	
#Event_Generator_Function_PYTHIA: Event_Generator_Function_PYTHIA.C
	g++ Event_Generator_Function_PYTHIA.C /Users/jordanlang/Applications/pythia8307/lib/libpythia8.a -o Event_Generator_Function_PYTHIA -I/Users/jordanlang/Applications/pythia8307/include -O2 -ansi -pedantic -W -Wall -Wshadow -fPIC -Wl,-rpath,/Users/jordanlang/Applications/pythia8307/lib -ldl `~/fastjet-install/bin/fastjet-config --cxxflags --libs --plugins` -ldl `root-config --libs --cflags`
